name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - refacto

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: refacto
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      ENV_CROWDIN_API_KEY: ${{ secrets.ENV_CROWDIN_API_KEY }}

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v4

      ## Need packages
      # curl / jq / csv / zip

      - name: Fetch Translations
        run: curl "https://api.crowdin.com/api/project/prestashop-official/status?key=${ENV_CROWDIN_API_KEY}&json" | jq -r '.[] | [.name, .approved_progress]| @csv' > ./data/languages.csv

      - name: Fetch Translators Hash
        run: curl "https://api.crowdin.com/api/project/prestashop-official/reports/top-members/export?key=${ENV_CROWDIN_API_KEY}&json&date_from=2016-01-01&format=csv" | jq -r .hash > translators_hash.csv

      - name: Fetch Translators
        run: curl "https://api.crowdin.com/api/project/prestashop-official/reports/top-members/download?key=${ENV_CROWDIN_API_KEY}&hash=$(cat translators_hash.csv)" >> data/translators.csv

      - name: Remove Translators Hash file
        run: rm translators_hash.csv

      - name: Setup node env ðŸ—
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules ðŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Install dependencies ðŸ’š
        working-directory: csv_to_json
        run: npm install

      - name: Generate statistics.json
        working-directory: csv_to_json
        run: npm start

      - name: Write CNAME file
        run: echo 'translators.prestashop-project.org' > ./public/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
